### ISSUE TITLE
It seems that STM32CubeMX is no longer in '/Applications/STMicroelectronics/STM32CubeMX.app/Contents/MacOs/STM32CubeMX' (or perhaps I am doing something wrong)

### ISSUE THREAD

**Issue by ubaldot** [ussserrr/stm32pio#118]
I have installed STM32CubeIDE. I setup a test project and I tried to run stm32pio. However, I get the following error: 

`ERROR    FileNotFoundError: [Errno 2] No such file or directory: '/Applications/STMicroelectronics/STM32CubeMX.app/Contents/MacOs/STM32CubeMX'`

In-fact, STM32CubeMX is not installed in that folder (I checked), but I could not find where it is installed. 
Perhaps  stm32pio shall searh STM32CubeMX in a different folder?

**Comment by ubaldot** [comment]
Really wrong question, sorry!

**Comment by Sercurio** [comment]
How do you fix the problem ? Got the same with MX installed vie brew
