### ISSUE TITLE
stm32pio generate -> Hardcode path to CubeMX 

### ISSUE THREAD

**Issue by creatormir** [ussserrr/stm32pio#27]
Hi.
I have a CubeMX on disk D in dir /prog . Where can I point this?

Quick solution, go to file:
....\Python38\Lib\site-packages\stm32pio\core\settings.py line 42
C:/Program Files/STMicroelectronics/STM32Cube/STM32CubeMX/STM32CubeMX.exe
to you patch

**Comment by creatormir** [comment]
I'm very apologies.
Everything is in the settings: 
stm32pio.ini
https://github.com/ussserrr/stm32pio/blob/master/docs/CONFIG.md

**Comment by ussserrr** [comment]
No worries.
