### ISSUE TITLE
platformio_cmd not found

### ISSUE THREAD

**Issue by Lutz1967** [ussserrr/stm32pio#30]
Hi,

Using CLI on MacOS10.13.6

Problem when running validate:

INFO     checking 'java_cmd'...
INFO     checking 'cubemx_cmd'...
INFO     checking 'platformio_cmd'...
[   ok]  java_cmd  
[   ok]  cubemx_cmd
[error]  platformio_cmd

how do I fix that? I use PlatformIO all the time in VSCode.
Thanks!

**Comment by ussserrr** [comment]
How do you install the PlatformIO? If it was PlatformIO IDE then you probably need to add _shell extensions_ so you (and stm32pio) can launch PlatformIO through the CLI. See [there](https://docs.platformio.org/en/latest/core/installation.html#piocore-install-shell-commands) for more information.

**Comment by Lutz1967** [comment]
Thanks - solved.

**Comment by Lutz1967** [comment]
Thanks for the quick answer.
